; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32s3_mini]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

; Definisce LittleFS come File System per la cartella data
board_build.filesystem = littlefs

; Assegna la partizione di memoria (es. 4MB/8MB per i file data)
board_build.partitions = default_8MB.csv

lib_deps =
    bitbank2/AnimatedGIF @ ^2.1.0
    lovyan03/LovyanGFX @ ^1.1.12